server:
  port: 8080
  servlet:
    context-path: /Bibased
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: chenfei
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true