server:
# 端口号
  port: 8080
  servlet:
# 路径
    context-path: /Bibased
spring:
# 数据库配置
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: chenfei
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 邮箱服务
  mail:
    host: smtp.163.com
    username: leizaifeizizaifei@163.com
    password: 597479975xff
    default-encoding: utf-8
    artemis:
        port: 587
    properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
mail.fromMail.addr: leizaifeizizaifei@163.com

